[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "analysis_project"
version = "1.0.0"
description = "Analysis Project - New Python Project for Stock Returns Analysis"

[tools.setuptools.packages.find]
where = ["src"]